language: java
install:
  # Download dependencies with JDK 8 because Maven Central supports
  # TLS 1.2 only but OpenJDK 6 does not.
  - export ORIGINAL_JAVA_HOME=$JAVA_HOME
  - jdk_switcher use oraclejdk8
  - mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true
  # Restore desired JDK
  - export JAVA_HOME=$ORIGINAL_JAVA_HOME
addons:
  apt:
    packages:
      - openjdk-6-jdk
      - openjdk-7-jdk
jdk:
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8
  - openjdk7
  - openjdk6
