language: java
install: mvn install -DskipTests -Dgpg.skip -Dmaven.javadoc.skip=true
addons:
  apt:
    packages:
      - openjdk-6-jdk
      - openjdk-7-jdk
jdk:
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8
  - openjdk7
